services:
  # Backend Service
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  # Frontend Service
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    env_file:
      - ./database/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis Cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Nginx Proxy
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
